# See https://pre-commit.com/hooks.html
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.9
  hooks:
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
# - repo: https://github.com/RobertCraigie/pyright-python
#   rev: v1.1.369
#   hooks:
#   - id: pyright
#     additional_dependencies: [ "rich", "fastapi", "python-multipart", "uvicorn", "PyJWT", "argon2-cffi", "pysqlite3-binary", "pywebpush", "py_vapid", "requests", "toml", "appdirs" ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
    - id: mypy
      additional_dependencies: ['types-requests', 'types-toml', 'types-PyYAML']
- repo: local
  hooks:
    - id: pytest-check
      # stages: [push]
      types: [python]
      name: pytest-check
      entry: python -m pytest
      language: system
      pass_filenames: false
      always_run: true
